heartbeat.monitors:
- type: http
  id: kibana-service
  name: Kibana
  urls: ["https://kibana:5601"]
  schedule: '@every 10s'
  ssl:
    enabled: true
    certificate_authorities: ["certs/ca/ca.crt"]
    certificate: "certs/es01/es01.crt"
    key: "certs/es01/es01.key"
    verification_mode: full

output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: "${ELASTIC_USER}"
  password: "${ELASTIC_PASSWORD}"
  ssl:
    enabled: true
    certificate_authorities: ["certs/ca/ca.crt"]
    certificate: "certs/es01/es01.crt"
    key: "certs/es01/es01.key"
    verification_mode: full

setup.kibana:
  host: "https://kibana:5601"
  username: "${ELASTIC_USER}"
  password: "${ELASTIC_PASSWORD}"
  ssl:
    enabled: true
    certificate_authorities: ["certs/ca/ca.crt"]
    certificate: "certs/es01/es01.crt"
    key: "certs/es01/es01.key"
    verification_mode: full

setup.dashboards.enabled: false
setup.template.enabled: true
