packetbeat.interfaces:
  device: any
  snaplen: 65535
  type: pcap

packetbeat.protocols:
- type: http
  ports: [80]
  send_headers: ["Host", "User-Agent"]
  send_request: true
- type: tcp
  ports: [9200, 5601]
- type: tls
  ports: [443, 5601, 9200]
  send_certificates: true
  send_handshake: true

output.elasticsearch:
  hosts: ["https://localhost:9200"]
  username: "${ELASTIC_USER}"
  password: "${ELASTIC_PASSWORD}"
  ssl:
    enabled: true
    certificate_authorities: ["certs/ca/ca.crt"]
    certificate: "certs/es01/es01.crt"
    key: "certs/es01/es01.key"
    verification_mode: full

setup.kibana:
  host: "https://localhost:5601"
  username: "${ELASTIC_USER}"
  password: "${ELASTIC_PASSWORD}"
  ssl:
    enabled: true
    certificate_authorities: ["certs/ca/ca.crt"]
    certificate: "certs/es01/es01.crt"
    key: "certs/es01/es01.key"
    verification_mode: full

setup.dashboards.enabled: false
setup.template.enabled: true
